const mongoose=require("mongoose");

const quizAttemptSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    quizType:{
        type:String,
        required:true,
        default:"full"
    },
    questions:[{
        question:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Question"
        },
        selectedAnswer:{
            type:String,
        },
        correctAnswer:{
            type:String
        },
        isCorrect:{
            type:Boolean
        }
    }],
    score:{
        type:Number,
        required:true
    },
    totalQuestions:{
        type:Number,
        required:true
    },
    percentage:{
        type:Number,
        required:true
    },
    completedAt:{
        type:Date,
        default:Date.now
    }
},
{
    timestamps:true
}
);

module.exports=mongoose.model("QuizAttempt",quizAttemptSchema);